### ISSUE TITLE
这个demo iPhoneX没有适配

### ISSUE THREAD

**Issue by pjyin** [SPStore/SPPageMenu#1]
iPhonex没有适配

**Comment by SPStore** [comment]
嗯，我现在还没有写iPhoneX呢，公司穷，买不起，不知道在iPhoneX上显示结果如何，但是框架应该跟iPhoneX没关系，只是我的例子没适配

**Comment by SPStore** [comment]
不对，我Xcode升级了，可以用模拟器，现在就去适配
