### ISSUE TITLE
希望可以多扩展几个代理方法

### ISSUE THREAD

**Issue by YuanJiaShuai** [SPStore/SPPageMenu#25]
1.点击到按钮的方法
2.滚动到按钮的方法
3.滚动到和点击到都会执行的方法

我现在有个需求就是点击最后一个按钮会弹出一个框，但是滚动到这个按钮的时不用弹出来，只有点击才弹出

**Comment by SPStore** [comment]
不用扩展就能实现你的需求。滚动到按钮，说明外界的scrollView肯定是经过手指拖拽的，此时外界的scollView的dragging属性为YES，通过这个属性就可以判断是拖拽还是点击了按钮

**Comment by YuanJiaShuai** [comment]
好的，多谢
